"""
Enhanced SVG Renderer - Professional Quality Rendering
======================================================

This module provides the EnhancedSVGRenderer which combines:
1. UniversalSVGRenderer for base rendering
2. EnhancedComponentLibrary for professional styling
3. Multiple rendering styles (Classic, Modern, 3D)

Features:
- Professional gradients and shadows
- Multiple rendering styles
- High-quality component visuals
- Optimized SVG output

Author: Universal Diagram Generator Team
Date: November 5, 2025
"""

from typing import Optional
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.universal_svg_renderer import UniversalSVGRenderer, ComponentLibrary
from core.enhanced_component_library import EnhancedComponentLibrary, ComponentStyle
from core.universal_scene_format import UniversalScene, SceneObject, Relationship


class EnhancedSVGRenderer:
    """
    Enhanced SVG Renderer with professional quality output

    Wraps UniversalSVGRenderer and adds:
    - Enhanced component library with multiple styles
    - Professional gradients and shadows
    - Optimized SVG generation
    """

    def __init__(self, component_library: Optional[EnhancedComponentLibrary] = None):
        """
        Initialize Enhanced SVG Renderer

        Args:
            component_library: Optional EnhancedComponentLibrary with custom style
        """
        # Initialize base renderer
        self.base_renderer = UniversalSVGRenderer()

        # Initialize enhanced component library
        self.component_library = component_library or EnhancedComponentLibrary()

        # Current style
        self.current_style = self.component_library.style

    def set_style(self, style: str):
        """
        Set rendering style

        Args:
            style: Style name ("classic", "modern", or "3d")
        """
        self.component_library.set_style(style)
        self.current_style = self.component_library.style

    def render(self, scene: UniversalScene) -> str:
        """
        Render a UniversalScene to SVG string

        Args:
            scene: UniversalScene object to render

        Returns:
            SVG string with professional quality rendering
        """
        # Build SVG structure
        svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     width="{scene.canvas_width}"
     height="{scene.canvas_height}"
     viewBox="0 0 {scene.canvas_width} {scene.canvas_height}">
    <title>{scene.title}</title>
    <desc>Generated by Universal STEM Diagram Generator - {scene.diagram_type}</desc>

    <!-- Definitions -->
    <defs>
        {self._generate_gradients()}
        {self._generate_filters()}
    </defs>

    <!-- Background -->
    <rect width="100%" height="100%" fill="{self.current_style.background_color}"/>

    <!-- Grid (optional) -->
    {self._generate_grid() if self.current_style.show_grid else ''}

    <!-- Components -->
    <g id="components">
        {self._render_components(scene)}
    </g>

    <!-- Connections -->
    <g id="connections">
        {self._render_connections(scene)}
    </g>

    <!-- Labels and Annotations -->
    <g id="annotations">
        {self._render_annotations(scene)}
    </g>
</svg>'''

        return svg

    def _generate_gradients(self) -> str:
        """Generate SVG gradient definitions"""
        return '''
        <!-- Gradients -->
        <linearGradient id="resistor_grad" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:#d4a574;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#8b7355;stop-opacity:1" />
        </linearGradient>
        <linearGradient id="capacitor_grad" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:#4a9eff;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#1e3a8a;stop-opacity:1" />
        </linearGradient>
        <linearGradient id="battery_grad" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:#22c55e;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#166534;stop-opacity:1" />
        </linearGradient>
        <radialGradient id="atom_grad" cx="50%" cy="50%" r="50%">
            <stop offset="0%" style="stop-color:#fbbf24;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#f59e0b;stop-opacity:1" />
        </radialGradient>'''

    def _generate_filters(self) -> str:
        """Generate SVG filter definitions for shadows"""
        if not self.current_style.show_shadows:
            return ''

        return '''
        <!-- Shadow Filter -->
        <filter id="shadow" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur in="SourceAlpha" stdDeviation="3"/>
            <feOffset dx="2" dy="2" result="offsetblur"/>
            <feComponentTransfer>
                <feFuncA type="linear" slope="0.3"/>
            </feComponentTransfer>
            <feMerge>
                <feMergeNode/>
                <feMergeNode in="SourceGraphic"/>
            </feMerge>
        </filter>'''

    def _generate_grid(self) -> str:
        """Generate background grid"""
        return '''
    <defs>
        <pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse">
            <path d="M 20 0 L 0 0 0 20" fill="none" stroke="#e0e0e0" stroke-width="0.5"/>
        </pattern>
    </defs>
    <rect width="100%" height="100%" fill="url(#grid)"/>'''

    def _render_components(self, scene: UniversalScene) -> str:
        """Render all scene components"""
        components_svg = []

        for obj in scene.objects:
            component_svg = self._render_component(obj)
            if component_svg:
                components_svg.append(component_svg)

        return '\n'.join(components_svg)

    def _render_component(self, obj: SceneObject) -> str:
        """Render a single component using enhanced library"""
        x, y = obj.position.x, obj.position.y
        w, h = obj.dimensions.width, obj.dimensions.height

        # Get appropriate rendering method from enhanced library
        component_type = obj.object_type.value.lower()

        try:
            if component_type == 'resistor':
                svg_elem = self.component_library.create_enhanced_resistor(
                    x, y, w, h, obj.label, 'horizontal'
                )
            elif component_type == 'capacitor':
                svg_elem = self.component_library.create_enhanced_capacitor(
                    x, y, w, h, obj.label, 'electrolytic'
                )
            elif component_type == 'battery':
                svg_elem = self.component_library.create_enhanced_battery(
                    x, y, w, h, obj.label, 1
                )
            elif component_type == 'atom':
                svg_elem = self.component_library.create_enhanced_atom(
                    x, y, w/2, obj.label, 3
                )
            else:
                # Fallback to simple rectangle
                return f'''<rect x="{x-w/2}" y="{y-h/2}" width="{w}" height="{h}"
                          fill="{obj.style.fill_color}"
                          stroke="{obj.style.stroke_color}"
                          stroke-width="{obj.style.stroke_width}"/>
                          <text x="{x}" y="{y}" text-anchor="middle" dy="0.3em">{obj.label}</text>'''

            return svg_elem.to_svg(indent=0)
        except Exception as e:
            print(f"Warning: Could not render {component_type}: {e}")
            return ''

    def _render_connections(self, scene: UniversalScene) -> str:
        """Render all connections between components"""
        connections_svg = []

        # Create object lookup
        objects_dict = {obj.id: obj for obj in scene.objects}

        for rel in scene.relationships:
            if rel.source_id not in objects_dict or rel.target_id not in objects_dict:
                continue

            source = objects_dict[rel.source_id]
            target = objects_dict[rel.target_id]

            # Draw connection line
            connection = f'''<line x1="{source.position.x}" y1="{source.position.y}"
                                  x2="{target.position.x}" y2="{target.position.y}"
                                  stroke="{self.current_style.primary_color}"
                                  stroke-width="2"
                                  stroke-linecap="round"/>'''
            connections_svg.append(connection)

        return '\n'.join(connections_svg)

    def _render_annotations(self, scene: UniversalScene) -> str:
        """Render annotations and labels"""
        annotations_svg = []

        for annotation in scene.annotations:
            # Render annotation text
            ann_svg = f'''<text x="{annotation.position.x}"
                               y="{annotation.position.y}"
                               font-size="{annotation.style.font_size}"
                               fill="{annotation.style.stroke_color}"
                               text-anchor="middle">{annotation.content}</text>'''
            annotations_svg.append(ann_svg)

        return '\n'.join(annotations_svg)

    def render_to_file(self, scene: UniversalScene, filename: str):
        """
        Render scene to SVG file

        Args:
            scene: UniversalScene to render
            filename: Output filename
        """
        svg_content = self.render(scene)
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(svg_content)


# Testing
if __name__ == "__main__":
    from core.universal_scene_format import create_circuit_scene, Position, Dimensions

    print("Enhanced SVG Renderer - Test")
    print("=" * 50)

    # Create test scene
    scene = create_circuit_scene("test", "Test Circuit")

    # Add components
    from core.universal_scene_format import SceneObject, ObjectType
    resistor = SceneObject(
        id="r1",
        object_type=ObjectType.RESISTOR,
        position=Position(200, 200, 0),
        dimensions=Dimensions(80, 40, 0),
        label="R1 = 100Ω"
    )
    scene.add_object(resistor)

    # Test rendering with each style
    renderer = EnhancedSVGRenderer()

    for style in ['classic', 'modern', '3d']:
        print(f"\nTesting {style} style...")
        renderer.set_style(style)
        svg = renderer.render(scene)
        print(f"  Generated {len(svg)} characters of SVG")

    print("\n" + "=" * 50)
    print("✅ Enhanced SVG Renderer ready!")
